{% set name = "pystan" %}
{% set version = "2.17.1.0" %}
{% set sha256sum = "d4f91b5300c002448c4141abb806264f929fffed4fb72b9dbdfd2def83529b78" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1004
  skip: True  # [win and py27]
  detect_binary_files_with_prefix: False

requirements:
  build:
    - posix                       # [win]
    - {{ compiler('c') }}         # [not win]
    - {{ compiler('m2w64_c') }}   # [win]
    - {{ compiler('cxx') }}       # [not win]
    - {{ compiler('m2w64_cxx') }} # [win]
  host:
    - python
    - setuptools
    - numpy
    - cython >=0.22,!=0.25.1
  run:
    # http://pystan.readthedocs.io/en/latest/windows.html
    # PyStan requires a C++ compiler for building models. For
    # full support of vectorized functions, gcc is recommended.
    - posix                       # [win]
    - {{ compiler('c') }}         # [not win]
    - {{ compiler('m2w64_c') }}   # [win]
    - {{ compiler('cxx') }}       # [not win]
    - {{ compiler('m2w64_cxx') }} # [win]
    - python
    - {{ pin_compatible('numpy') }}
    - cython >=0.22,!=0.25.1
    - matplotlib

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/interfaces/pystan.html
  license: GPLv3
  license_file: LICENSE
  summary: Python interface to Stan, a package for Bayesian inference
  description: |
    PyStan provides a Python interface to Stan, a package for Bayesian
    inference using the No-U-Turn sampler, a variant of Hamiltonian Monte
    Carlo.
  doc_url: https://pystan.readthedocs.org/
  dev_url: https://github.com/stan-dev/pystan

extra:
  recipe-maintainers:
    - rmax
    - beckermr
