{% set name = "pystan" %}
{% set version = "2.19.1.1" %}
{% set sha256sum = "fa8bad8dbc0da22bbe6f36af56c9abbfcf10f92df8ce627d59a36bd8d25eb038" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa8bad8dbc0da22bbe6f36af56c9abbfcf10f92df8ce627d59a36bd8d25eb038

build:
  skip: true  # [win]
  number: 1
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    # http://pystan.readthedocs.io/en/latest/windows.html
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - python
    - pip
    - numpy
    - cython >=0.22,!=0.25.1
    - scipy
    - setuptools
    - libpython  # [win]
  run:
    - python
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    # http://pystan.readthedocs.io/en/latest/windows.html
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]  
    - {{ pin_compatible('numpy') }}
    - cython >=0.22,!=0.25.1
    - setuptools
    - scipy
    - matplotlib-base
    - arviz
    - libpython  # [win]

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/interfaces/pystan.html
  license: GPLv3
  license_file: LICENSE
  summary: Python interface to Stan, a package for Bayesian inference
  description: |
    PyStan provides a Python interface to Stan, a package for Bayesian
    inference using the No-U-Turn sampler, a variant of Hamiltonian Monte
    Carlo.
  doc_url: https://pystan.readthedocs.org/
  dev_url: https://github.com/stan-dev/pystan

extra:
  recipe-maintainers:
    - rmax
    - beckermr
