{% set name = "pystan" %}
{% set version = "3.2.0" %}
{% set sha256sum = "aab87b5d1443ff41d786bd8770d1ce03c3c695adcb309c2cfa2c4ea95bd332ab" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1
  skip: True  # [win or py36]

requirements:
  build:
    - {{ compiler('cxx') }} 
  host:
    - python
    - pip
    - numpy
    - scipy
    - setuptools
    - poetry 
  run:
    - python
    - {{ compiler('cxx') }}
    - {{ pin_compatible('numpy') }}
    - setuptools
    - clikit >=0.6,<0.7
    - httpstan >=4.5,<4.6
    - pysimdjson >=3.2
    - aiohttp >=3.6

test:
  imports:
    - stan
    - stan.common
    - stan.fit
    - stan.model
    - stan.plugins

about:
  home: http://mc-stan.org/interfaces/pystan.html
  license: ISC
  license_file: LICENSE
  summary: Python interface to Stan, a package for Bayesian inference
  description: |
    PyStan provides a Python interface to Stan, a package for Bayesian
    inference using the No-U-Turn sampler, a variant of Hamiltonian Monte
    Carlo.
  doc_url: https://pystan.readthedocs.org/
  dev_url: https://github.com/stan-dev/pystan

extra:
  recipe-maintainers:
    - rmax
    - dhirschfeld
    - mxr-conda
