{% set name = "pystan" %}
{% set version = "2.18.0.0" %}
{% set sha256sum = "594c1523fd5cd6034ba1b58b1a0741f7e753c819d17745395defa25e526115ce" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - 0001-Add-compiler-flag-for-realigning-stack.patch
    - 0002-Replace-logger-with-print.patch

build:
  number: 1003
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-patch                     # [win]
  host:
    - python
    - setuptools
    - numpy
    - cython >=0.22,!=0.25.1
  run:
    # https://pystan.readthedocs.io/en/latest/getting_started.html
    # "PyStan also requires that a C++ compiler be available to
    #  Python during installation and at runtime."
    - {{ compiler('cxx') }}  # [not win]
    # https://pystan.readthedocs.io/en/latest/windows.html
    # PyStan requires a C++ compiler for building models. For
    # full support of vectorized functions, gcc is recommended.
    - m2w64-toolchain        # [win]
    - python
    - {{ pin_compatible('numpy') }}
    - cython >=0.22,!=0.25.1
    - matplotlib

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/interfaces/pystan.html
  license: GPLv3
  license_file: LICENSE
  summary: Python interface to Stan, a package for Bayesian inference
  description: |
    PyStan provides a Python interface to Stan, a package for Bayesian
    inference using the No-U-Turn sampler, a variant of Hamiltonian Monte
    Carlo.
  doc_url: https://pystan.readthedocs.org/
  dev_url: https://github.com/stan-dev/pystan

extra:
  recipe-maintainers:
    - rmax
