# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython2.7
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython3.6
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython3.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython2.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.6
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IJgErpLtO9mXEPF9yXMe9WXUKzq+Vq2RZkD4RmExMS3cgdoEOiBQ7hDlnyFkcyFSKDLAv7tOgokaPuau6WNf0Dxdi6whwGnZiVfRB8SfJFaWFfy2mCvbBQrcI6+S2QDl0IcM6WIfd3D/9QKPF6UC9YTzCPku4s8SyHYRb83JkvA4vWKzxkmENrCWL6B3At32UJDsTGFkVQK4KttA2ZlFAgMUnF6pX4k+SK8JiI5gp/Rrh9mElNvr+C/r0GfG9sqIMhIefQkEsnJ8gTqlHv79UbC8u4GH5aYqZeaRigBASEtocQJEYMp/+4SQygyARAtKpnLKB0bHhzIb9c/aQdJf2CrP45daXYRvE6HW/9t2q9663IZupwFFhbKJTmlv6sPvNxHD64n2ewzqePPa6FE1LYNedtur8XotlfhcVOKYsQsna94gges/JoA0EJXm9oKMJpWFF8StSQeck/13aMGWXVDLnUMOUEBriS3Fwv7gnDS7q+HF7CWcEa3L12Aw4REpiXOUHWi6Zg3l+AzjbbG5NZqoZhEG8JPgKpja1e1KS5SfufUm8yVLxnYLutZvmmpZZ0JBTmq5nqA+i/40Y3GEkRBqNmlN9QsOnHEoJF8+9cn2htjgoWEp2z8Z0ejqcdqEObepDqNtj5+E0tI+0aWqv/1zuOOy9cuoAc1kCSKXy5A="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml